### ISSUE TITLE
Missing Documentation (README)

### ISSUE THREAD

**Issue by mcronberg** [garyexplains/aitray#1]
Great app and idea!!! 

The project seems to lack a comprehensive README file that covers essential details about the application. It would be helpful to include the following information:  

1. **Application Overview**: A brief explanation of what the app does and its intended purpose.  
2. **How to Compile/Install**: Detailed steps for compiling and installing the application, including any dependencies or prerequisites.  
3. **Usage Instructions**: Guidance on how to run and use the app effectively.  
4. **Handling Private Information**: A note about being cautious with private or sensitive information when using the app.  
5. **Contributing Guidelines**: If contributions are welcome, include clear instructions for contributors.  

Adding this documentation will make the project more accessible and user-friendly for the community. 

Let me know if you have any comments or if you’d like me to draft a PR for this!

**Comment by garyexplains** [comment]
Hi. I agree 100%. If you have time please go ahead and draft a PR for this.
