### ISSUE TITLE
Consider Upgrading to .NET 9

### ISSUE THREAD

**Issue by mcronberg** [garyexplains/aitray#3]
Consider updating the project to use .NET 9 for the following reasons:

- Ease of Access: Beginners often download the latest SDK available, which is currently .NET 9. Keeping the project aligned with the latest version reduces confusion for new contributors.
- Improved Features: .NET 9 offers new features and performance improvements that could benefit the project in the future

**Comment by garyexplains** [comment]
Valid points, but I think .NET 8 is the long-term support version at the moment, so it is best to stay with that. However, it is a trivial upgrade if/when needed.
